/aruco_node:
  ros__parameters:
    marker_size: 0.1
    aruco_dictionary_id: DICT_4X4_100
    image_topic: /camera
    intrinsic_matrix: [1.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    distortion: [0.0, 0.0, 0.0, 0.0]